SalesForceLeadMessages/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SalesForceLeadMessages.Models;


namespace SalesForceLeadMessages.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            if (Request.QueryString.HasKeys() && Request.QueryString != null)
            {
                ViewBag.token = Request.QueryString["token"].ToString();
                ViewBag.apiVersion = Request.QueryString["api"].ToString();
                ViewBag.instanceUrl = Request.QueryString["instance_url"].ToString();
                ViewBag.LoggedIn = true;

                string test = null;

                string gitTest = "Get test change";

                var leads = new Lead().GetLeads(Request.QueryString["instance_url"].ToString(), Request.QueryString["api"].ToString(), Request.QueryString["token"].ToString());

            }
            else
            {
                ViewBag.LoggedIn = false;
            }

            return View();
        }

    }
}

SalesForceLeadMessages/Controllers/SalesforceLoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;
using System.Net;
using System.Configuration;
using System.Collections.Specialized;
using System.Text;
using Newtonsoft.Json;
using System.Web.Script.Serialization;
using SalesForceLeadMessages.Models;
using System.Web.Http;
using System.Threading.Tasks;
using Newtonsoft.Json.Linq;
using Salesforce.Common;
using Salesforce.Common.Models;

namespace SalesForceLeadMessages.Controllers
{


    public class SalesforceLoginController : Controller
    {

        private readonly string _authorizeEndpointUrl = ConfigurationSettings.AppSettings["AuthorizationEndpointUrl"];
        private readonly string _consumerKey = ConfigurationSettings.AppSettings["ConsumerKey"];
        private readonly string _consumerSeceret = ConfigurationSettings.AppSettings["ConsumerSeceret"];
        private readonly string _callbackUrl = ConfigurationSettings.AppSettings["CallbackUrl"];

        //
        // GET: /SalesforceLogin/
        public ActionResult Index()
        {
            //return "Ok";
            var url = Common.FormatAuthUrl(_authorizeEndpointUrl, ResponseTypes.Code, _consumerKey, HttpUtility.UrlEncode(_callbackUrl));

            return Redirect(url);
        }
	}
}

SalesForceLeadMessages/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-12">
        <h2>Hi! Welcome to the salesforce message app.</h2>
        <p>
            Before you get started, you must first log in to salesforce. :)
            <hr />
            @Html.ActionLink("Login", "Index", "SalesforceLogin")
        </p>
    </div>
    <hr />

    <ul>
        <li><b>Access token: </b>@ViewBag.Token</li>
        <li><b>Api version: </b>@ViewBag.ApiVersion</li>
        <li><b>Instance Url: </b>@ViewBag.InstanceUrl</li>
    </ul>